apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-role-config
data:
  # redis.conf: |
  #   bind 0.0.0.0
  #   port 6379
  #   protected-mode no
  #   appendonly yes
  #   dir /redis/data
  primary.conf: |
    bind 0.0.0.0
    port 6379
    protected-mode no
    appendonly yes
    dir /redis/data
  replica.conf: |
    replicaof redis-0.redis 6379
    bind 0.0.0.0
    port 6379
    protected-mode no
    appendonly yes
    dir /redis/data
