apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-app
spec:
  ingressClassName: nginx
  rules:
    - host: k8s.app.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: k8s-app
                port:
                  number: 8899

          # - path: /robohash
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: robohash
          #       port:
          #         number: 80
