apiVersion: v1
kind: Service
metadata:
  name: k8s-app
spec:
  # type: ClusterIP
  # type: LoadBalancer
  type: NodePort
  selector:
    app: k8s-app
  ports:
    - port: 8899
      targetPort: 9090
      protocol: TCP
